<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 2.11.11 setup script by Michal Čihař <michal@cihar.com>
 * Version: $Id$
 * Date: Sat, 18 Aug 2012 05:28:16 GMT
 */

/* Servers configuration */
$i = 0;

/* Server localhost (cookie) [1] */
$i++;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['extension'] = 'mysql';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'ba17c1ec07d65003';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>
